version: '3.1'

services:

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 025568
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080